# Generated by Django 5.0 on 2025-09-26 12:00
# Dummy migration to fix missing migration in chain

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0012_alter_country_neighbours'),
    ]

    operations = [
        # Empty operations - this migration exists only to maintain
        # the migration chain continuity
    ]
