# Generated by Django 5.0 on 2025-09-26 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0013_alter_alternativename_id_alter_city_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('country', 'region', 'id', 'name')},
        ),
        migrations.RemoveField(
            model_name='city',
            name='subregion',
        ),
        migrations.AddField(
            model_name='city',
            name='subregion',
            field=models.ManyToManyField(blank=True, related_name='cities', to='cities.subregion'),
        ),
    ]
